name: softwars_todo
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: 3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  provider: 6.1.2
  http: 1.2.2
  flutter_dotenv: 5.2.1
  image_picker: 1.1.2
  date_picker_plus: 4.1.0
  intl: 0.20.1
  uuid: 4.5.1
  shared_preferences: 2.3.4
  connectivity_plus: 6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: SF-UI-Display
      fonts:
        - asset: assets/fonts/sf-ui-display-black.otf
        - asset: assets/fonts/sf-ui-display-bold.otf
        - asset: assets/fonts/sf-ui-display-heavy.otf
        - asset: assets/fonts/sf-ui-display-light.otf
        - asset: assets/fonts/sf-ui-display-medium.otf
        - asset: assets/fonts/sf-ui-display-semibold.otf
        - asset: assets/fonts/sf-ui-display-thin.otf
        - asset: assets/fonts/sf-ui-display-ultralight.otf
